### ISSUE TITLE
dev-haskell/haddock-api-2.24.0 fails to build with ghc-8.10.2

### ISSUE THREAD

**Issue by l29ah** [gentoo-haskell/gentoo-haskell#1093]
```
[11 of 40] Compiling Haddock.GhcUtils ( src/Haddock/GhcUtils.hs, dist/build/Haddock/GhcUtils.o, dist/build/Haddock/GhcUtils.dyn_o )

src/Haddock/GhcUtils.hs:60:42: error:
    • Could not deduce: p ~ GhcPass p0
      from the context: (SrcSpanLess (LPat p) ~ Pat p,
                         HasSrcSpan (LPat p))
        bound by the type signature for:
                   getMainDeclBinder :: forall p.
                                        (SrcSpanLess (LPat p) ~ Pat p, HasSrcSpan (LPat p)) =>
                                        HsDecl p -> [IdP p]
        at src/Haddock/GhcUtils.hs:(58,1)-(59,40)
      ‘p’ is a rigid type variable bound by
        the type signature for:
          getMainDeclBinder :: forall p.
                               (SrcSpanLess (LPat p) ~ Pat p, HasSrcSpan (LPat p)) =>
                               HsDecl p -> [IdP p]
        at src/Haddock/GhcUtils.hs:(58,1)-(59,40)
      Expected type: TyClDecl (GhcPass p0)
        Actual type: TyClDecl p
    • In the first argument of ‘tcdName’, namely ‘d’
      In the expression: tcdName d
      In the expression: [tcdName d]
    • Relevant bindings include
        d :: TyClDecl p (bound at src/Haddock/GhcUtils.hs:60:28)
        getMainDeclBinder :: HsDecl p -> [IdP p]
          (bound at src/Haddock/GhcUtils.hs:60:1)
   |
60 | getMainDeclBinder (TyClD _ d) = [tcdName d]
   |                                          ^
```

**Comment by solpeth** [comment]
See upstream bug https://github.com/haskell/haddock/issues/1229
