### ISSUE TITLE
hledger-ui-1.27.1 doesn't compile with brick 1.5

### ISSUE THREAD

**Issue by amano-kenji** [gentoo-haskell/gentoo-haskell#1370]
```
Hledger/UI/UIUtils.hs:119:34: error:
    • No instance for (Data.String.IsString (Widget Name))
        arising from the literal ‘"Help (LEFT/ESC/?/q to close help)"’
    • In the first argument of ‘Just’, namely
        ‘"Help (LEFT/ESC/?/q to close help)"’
      In the first argument of ‘dialog’, namely
        ‘(Just "Help (LEFT/ESC/?/q to close help)")’
      In the first argument of ‘renderDialog’, namely
        ‘(dialog
            (Just "Help (LEFT/ESC/?/q to close help)") Nothing
            (c ^. availWidthL))’
```

This can be fixed by upgrading hledger-ui to 1.28 which seems to support brick-1.5.

**Comment by amano-kenji** [comment]
According to my test, fsnotify-0.4.1.0, hledger-lib-1.28, hledger-1.28, and hledger-ui-1.28 are needed.

**Comment by hololeap** [comment]
Thanks for reporting.
