### ISSUE TITLE
dev-haskell/stack-2.7.6_pre20220812 fails to build with fsnotify 4.1.0

### ISSUE THREAD

**Issue by Ultimator14** [gentoo-haskell/gentoo-haskell#1371]
### Error message

```
[ 11 of 110] Compiling Stack.FileWatch  ( src/Stack/FileWatch.hs, dist/build/Stack/FileWatch.o, dist/build/Stack/FileWatch.dyn_o )

src/Stack/FileWatch.hs:30:49: error: Not in scope: ‘confUsePolling’
   |
30 | fileWatchPoll = fileWatchConf $ defaultConfig { confUsePolling = True }
   |  
```

### Upstream patch

https://github.com/commercialhaskell/stack/commit/aef5ec042059fa7d9c71822bc7d8ab4f1be34ced

**Comment by hololeap** [comment]
Thanks for reporting and for the patch. This should be an easy fix.

**Comment by hololeap** [comment]
It looks like they just pushed a new version a few days ago.
