### ISSUE TITLE
www-servers/yesod-bin fails to compile

### ISSUE THREAD

**Issue by houseofsuns** [gentoo-haskell/gentoo-haskell#1505]
On my ~amd64 machine I see the following error  when trying to merge yesod-bin:

```
[5 of 7] Compiling Options          ( Options.hs, dist/build/yesod/yesod-tmp/Options.dyn_o )

Options.hs:70:14: error:
    • The constructor ‘CmdReader’ should have 2 arguments, but has been given 3
    • In the pattern: CmdReader _ cmds f
      In the pattern: Option (CmdReader _ cmds f) props
      In a stmt of a pattern guard for
                     an equation for ‘injectDefaultP’:
        (Option (CmdReader _ cmds f) props) <- o
   |
70 |   | (Option (CmdReader _ cmds f) props) <- o  =
   |              ^^^^^^^^^^^^^^^^^^
```

Full build log: [yesod-bin-1.6.2.2:20231125-205445.log](https://github.com/gentoo-haskell/gentoo-haskell/files/13465284/yesod-bin-1.6.2.2.20231125-205445.log)

Let me know if some additional info is required.

**Comment by hololeap** [comment]
Found it reported upstream here:

https://github.com/yesodweb/yesod/issues/1804

**Comment by hololeap** [comment]
I made a PR upstream: https://github.com/yesodweb/yesod/pull/1829

It compiles on `optparse-applicative` (both `0.17` and `0.18`). I can add it as a patch if you want to test it.

**Comment by hololeap** [comment]
The patch has been added if you want to sync and try it out. Let me know if it behaves the way you expect (especially any command line options/functionality which is what the patch modifies).
