### ISSUE TITLE
dev-haskell/jupyter: Fails to build on `ghc-8.10.5-r1`

### ISSUE THREAD

**Issue by hololeap** [gentoo-haskell/gentoo-haskell#1214]
```
[6 of 8] Compiling Jupyter.ZeroMQ   ( src/Jupyter/ZeroMQ.hs, dist/build/Jupyter/ZeroMQ.o, dist/build/Jupyter/ZeroMQ.dyn_o )

src/Jupyter/ZeroMQ.hs:480:24: error:
    • No instance for (MonadFail (ZMQ z)) arising from a use of ‘fail’
    • In the expression:
        fail
          "fatal error (Jupyter.ZeroMQ): Could not find port to connect to."
      In an equation for ‘findOpenPort’:
          findOpenPort 0 _
            = fail
                "fatal error (Jupyter.ZeroMQ): Could not find port to connect to."
      In an equation for ‘connectSocket’:
          connectSocket mProfile startPort accessor sock
            = do case mProfile of
                   Just _ -> connect sock (extractAddress mProfile accessor)
                   Nothing -> findOpenPort 100 startPort
                 endpoint sock
            where
                findOpenPort :: Int -> Int -> ZMQ z ()
                findOpenPort 0 _
                  = fail
                      "fatal error (Jupyter.ZeroMQ): Could not find port to connect to."
                findOpenPort triesLeft tryPort
                  = let ... in flip catch handler $ do ...
    |
480 |     findOpenPort 0 _ = fail "fatal error (Jupyter.ZeroMQ): Could not find port to connect to."
    |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Jupyter/ZeroMQ.hs:514:18: error:
    • No instance for (MonadFail (ZMQ z)) arising from a use of ‘fail’
    • In the expression:
        fail
          "fatal error (Jupyter.ZeroMQ): could not parse port as integer."
      In a case alternative:
          Nothing
            -> fail
                 "fatal error (Jupyter.ZeroMQ): could not parse port as integer."
      In a stmt of a 'do' block:
        case parsePort endpointString of
          Nothing
            -> fail
                 "fatal error (Jupyter.ZeroMQ): could not parse port as integer."
          Just port -> return port
    |
514 |     Nothing   -> fail "fatal error (Jupyter.ZeroMQ): could not parse port as integer."
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by hololeap** [comment]
The last upload for this package is `2016-08-14` and the source repo is missing:

http://github.com/gibiansky/haskell-jupyter

Still, I'll see if I can get it to a usable state and mask for removal if it seems too broken/outdated.

**Comment by hololeap** [comment]
Looks like that was a mistake in the cabal file. The repo still exits, although it hasn't been updated for years: https://github.com/gibiansky/jupyter-haskell

**Comment by hololeap** [comment]
Fixed by #1215
