### ISSUE TITLE
dev-haskell/yaml-0.11.10.0 fails to build with ghc-9.2.8

### ISSUE THREAD

**Issue by implr** [gentoo-haskell/gentoo-haskell#1422]
Rebuilds fail after the update from https://github.com/gentoo-haskell/gentoo-haskell/commit/370997d6f54761d71f36f0538df04220f96001b9 with this error:
```
[ 1 of 10] Compiling Data.Yaml.Internal ( src/Data/Yaml/Internal.hs, dist/build/Data/Yaml/Internal.o, dist/build/Data/Yaml/Internal.dyn_o )

src/Data/Yaml/Internal.hs:148:3: error:
    Ambiguous occurrence ‘AesonException’
    It could refer to
       either ‘Data.Aeson.AesonException’,
              imported from ‘Data.Aeson’ at src/Data/Yaml/Internal.hs:37:1-17
           or ‘Data.Yaml.Internal.AesonException’,
              defined at src/Data/Yaml/Internal.hs:98:23
    |
148 |   AesonException s -> "Aeson exception:\n" ++ s
    |   ^^^^^^^^^^^^^^

src/Data/Yaml/Internal.hs:366:26: error:
    Ambiguous occurrence ‘AesonException’
    It could refer to
       either ‘Data.Aeson.AesonException’,
              imported from ‘Data.Aeson’ at src/Data/Yaml/Internal.hs:37:1-17
           or ‘Data.Yaml.Internal.AesonException’,
              defined at src/Data/Yaml/Internal.hs:98:23
    |
366 |         Left e -> Left $ AesonException e
    |                          ^^^^^^^^^^^^^^

src/Data/Yaml/Internal.hs:374:26: error:
    Ambiguous occurrence ‘AesonException’
    It could refer to
       either ‘Data.Aeson.AesonException’,
              imported from ‘Data.Aeson’ at src/Data/Yaml/Internal.hs:37:1-17
           or ‘Data.Yaml.Internal.AesonException’,
              defined at src/Data/Yaml/Internal.hs:98:23
    |
374 |         Left e -> Left $ AesonException e
    |                          ^^^^^^^^^^^^^^
```

**Comment by hololeap** [comment]
Looks like https://github.com/snoyberg/yaml/issues/211, so this actually has to do with https://github.com/gentoo-haskell/gentoo-haskell/commit/547dd773bcc3b76b0ab0e68cfa0bdd7d0aaf32cd.

They have a fix that I'll pull in: https://github.com/snoyberg/yaml/pull/212

**Comment by hololeap** [comment]
@implr @amano-kenji

Let me know if https://github.com/gentoo-haskell/gentoo-haskell/commit/7bb38ac22826834ce87f32f253e14b193e9d4c0e works. I can't test it on my system right now.

**Comment by GuillaumedeVolpiano** [comment]
For what it's worth, I had the same issue (I came here to post the issue about 10 minutes after @implr had) and https://github.com/gentoo-haskell/gentoo-haskell/commit/7bb38ac22826834ce87f32f253e14b193e9d4c0e fixes it for me.

**Comment by hololeap** [comment]
Thanks @GuillaumedeVolpiano, I'll mark it as complete.
