### ISSUE TITLE
hadrian-9.10.1: build error, Not in scope: ‘C.initialBuildSteps’

### ISSUE THREAD

**Issue by Miezhiko** [gentoo-haskell/gentoo-haskell#1584]
trying to build with 9.8.4

```
[100 of 107] Compiling Hadrian.Haskell.Cabal.Parse ( src/Hadrian/Haskell/Cabal/Parse.hs, dist/build/hadrian/hadrian-tmp/Hadrian/Haskell/Cabal/Parse.o )

src/Hadrian/Haskell/Cabal/Parse.hs:413:9: error: [GHC-76037]
    Not in scope: ‘C.initialBuildSteps’
    NB: neither ‘Distribution.Simple’, ‘Distribution.Simple.Build’,
                ‘Distribution.Simple.Compiler’, ‘Distribution.Simple.Configure’,
                ‘Distribution.Simple.PackageDescription’,
                ‘Distribution.Simple.PackageIndex’,
                ‘Distribution.Simple.Program.Builtin’,
                ‘Distribution.Simple.Program.Db’,
                ‘Distribution.Simple.Program.Types’,
                ‘Distribution.Simple.Register’, ‘Distribution.Simple.Utils’,
                ‘Distribution.Types.ComponentLocalBuildInfo’,
                ‘Distribution.Types.LocalBuildInfo’, ‘Distribution.Verbosity’,
                ‘Distribution.ModuleName’, ‘Distribution.Package’,
                ‘Distribution.PackageDescription’,
                ‘Distribution.PackageDescription.Configuration’,
                ‘Distribution.Text’, ‘Distribution.Types.MungedPackageId’,
                ‘Distribution.Utils.Path’ nor ‘Distribution.Utils.ShortText’ export ‘initialBuildSteps’.
    |
413 |         C.initialBuildSteps cPath pd (lbi { C.localPkgDescr = pd }) C.silent
    |         ^^^^^^^^^^^^^^^^^^^
```

**Comment by markwright** [comment]
I wonder if this commit helps: https://github.com/gentoo-haskell/gentoo-haskell/commit/19e11f03d6abcdbf5e47863f22706b386ce59956

**Comment by markwright** [comment]
This is the issue where upstream removed this API: https://github.com/haskell/cabal/issues/9856
