### ISSUE TITLE
dev-haskell/stack-2.1.3.1: Ambiguous occurrence 'replaceExentsion'

### ISSUE THREAD

**Issue by Uroc327** [gentoo-haskell/gentoo-haskell#1037]
Emerging stack fails on my system with the following error message

```
[ 74 of 110] Compiling Stack.Package    ( src/Stack/Package.hs, dist/build/Stack/Package.o )

src/Stack/Package.hs:466:23: error:
    Ambiguous occurrence ‘replaceExtension’
    It could refer to either ‘FL.replaceExtension’,
                             imported from ‘Path’ at src/Stack/Package.hs:55:1-27
                             (and originally defined in ‘Path.Posix’)
                          or ‘FilePath.replaceExtension’,
                             imported from ‘System.FilePath’ at src/Stack/Package.hs:69:35-50
                             (and originally defined in ‘System.FilePath.Posix’)
    |
466 |         parseRelFile (replaceExtension (toFilePath relCFilePath) "o")
    |                       ^^^^^^^^^^^^^^^^
```

[build.log](https://github.com/gentoo-haskell/gentoo-haskell/files/4168672/build.log) is attached.

**Comment by solpeth** [comment]
We recently bumped `path` to 0.7. I believe this is the cause of the conflict. I'll either downgrade `path` or patch `stack`.

**Comment by solpeth** [comment]
@Uroc327 I've patched `stack` to build with `path-0.7`. Let me know if the issue still exists for you.
