### ISSUE TITLE
gitit-0.13.0.0 fails to build with pandoc-2.12

### ISSUE THREAD

**Issue by trofi** [gentoo-haskell/gentoo-haskell#1167]
Looks like minor API change is needed:

```
[13 of 22] Compiling Network.Gitit.Util ( src/Network/Gitit/Util.hs, dist/build/Network/Gitit/Util.o, dist/build/Network/Gitit/Util.dyn_o )

src/Network/Gitit/Util.hs:48:30: error:
    • Couldn't match type ‘Text’ with ‘[Char]’
      Expected type: FilePath -> IO String
        Actual type: FilePath -> IO Text
    • In the second argument of ‘(.)’, namely ‘UTF8.readFile’
      In the expression: fmap T.pack . UTF8.readFile
      In an equation for ‘readFileUTF8’:
          readFileUTF8 = fmap T.pack . UTF8.readFile
   |
48 | readFileUTF8 = fmap T.pack . UTF8.readFile
   |                              ^^^^^^^^^^^^^
```
